#include <iostream>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <string>
#include <vector>
#include <fstream>
#include <cstring>
#include <cstdio>
#include <stdlib.h>
#include <arpa/inet.h>
#include "convert.h"
#include "funtions.h"
#include "bin.h"
#include "headtrace.h"